{{- range $realmName, $realmDef := .Values.realms }}
{{- if $realmDef }}
{{- range ($realmDef.clients | default list) }}
{{- if not .publicClient }}
---
{{- $clientId := tpl .clientId $ }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $clientId }}
  labels:
    {{- include "keycloak-init.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $secretKey := "client_secret" }}
  {{- $existingSecret := (lookup "v1" "Secret" $.Release.Namespace $clientId) }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data $secretKey) }}
  {{ $secretKey }}: {{ index $existingSecret.data $secretKey }}
  {{- else }}
  {{ $secretKey }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
