{{- $suffix := tpl .Values.suffix . }}
{{- $ctx := merge (dict "suffix" $suffix) . }}
{{- range $realmName, $realmDef := .Values.realms }}
{{- range $realmDef.clients }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .clientId $ctx }}
  labels:
    {{- include "keycloak-init.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $secretName := tpl .clientId $ctx }}
  {{- $secretKey := "client_secret" }}
  {{- $existingSecret := (lookup "v1" "Secret" $.Release.Namespace $secretName) }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data $secretKey) }}
  {{ $secretKey }}: {{ index $existingSecret.data $secretKey }}
  {{- else }}
  {{ $secretKey }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
