{{- range .Values.clients }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .clientId }}
  labels:
    {{- include "keycloak-init.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- $secretName := .clientId }}
  {{- $secretKey := "client_secret" }}
  {{- $existingSecret := (lookup "v1" "Secret" $.Release.Namespace $secretName) }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data $secretKey) }}
  {{ $secretKey }}: {{ index $existingSecret.data $secretKey }}
  {{- else }}
  {{ $secretKey }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
