apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-init.fullname" . }}-config
  labels:
    {{- include "keycloak-init.labels" . | nindent 4 }}
data:
  clients.yaml: |
    realms:
    {{- $suffix := tpl .Values.suffix . }}
    {{- $ctx := merge (dict "suffix" $suffix) . }}
    {{- range $realmName, $realmDef := .Values.realms }}
      {{ tpl $realmName $ctx }}:
        clients:
        {{- toYaml $realmDef.clients | nindent 8 }}
    {{- end }}
