apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-init.fullname" . }}-config
  labels:
    {{- include "keycloak-init.labels" . | nindent 4 }}
data:
  clients.yaml: |
    clients:
    {{- toYaml .Values.clients | nindent 6 }}
