apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keycloak-init.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "keycloak-init.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "keycloak-init.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KEYCLOAK_URL
              value: {{ tpl (coalesce .Values.keycloak.url .Values.global.keycloakBaseUrl) . | quote }}
            - name: KEYCLOAK_USER
              value: {{ .Values.keycloak.user | quote }}
            - name: KEYCLOAK_PASSWORD
              {{- if .Values.keycloak.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.existingSecret }}
                  key: {{ .Values.keycloak.existingSecretKey }}
              {{- else }}
              value: {{ .Values.keycloak.password | quote }}
              {{- end }}
            - name: INPUT_FILE
              value: "/config/clients.yaml"
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- range $realmName, $realmDef := .Values.realms }}
            {{- range $realmDef.clients }}
            - name: secret-{{ .clientId }}
              mountPath: /secrets/{{ .clientId }}
              readOnly: true
            {{- end }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "keycloak-init.fullname" . }}-config
        {{- range $realmName, $realmDef := .Values.realms }}
        {{- range $realmDef.clients }}
        - name: secret-{{ .clientId }}
          secret:
            secretName: {{ .clientId }}
            items:
              - key: client_secret
                path: client_secret
        {{- end }}
        {{- end }}
