apiVersion: v2
name: keycloak-init
description: Helm chart to initialize Keycloak clients
type: application
version: 1.1.0
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P Keycloak Init"
  openg2p.org/add-to-rancher: "openg2p.org/add-to-rancher"
