image:
  repository: openg2p/keycloak-init
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "develop"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

keycloak:
  # Internal service name on the cluster
  url: "http://keycloak"
  user: "client-manager@openg2p.org" 
  # Use secret instead of directly passing password here
  password: ""
  realm: "master"
  # If you want to use an existing secret for password
  existingSecret: "keycloak-client-manager" 
  existingSecretKey: "keycloak-client-manager-password"

clients: 
  - clientId: "test-client-local"
    name: "Test Client Local"
    redirectUris: 
      - "*"
#    secret: "optional-secret-value" (If not provided, a random secret is generated and stored in a K8s Secret)

job:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
