image:
  repository: openg2p/keycloak-init
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "develop"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

global:
  keycloakBaseUrl: ""

keycloak:
  # Keycloak URL. If empty, falls back to global.keycloakBaseUrl
  url: "https://keycloak2.openg2p.org"
  user: "admin"
  # Use secret instead of directly passing password here
  password: ""
  # If you want to use an existing secret for password
  existingSecret: "keycloak-admin"
  existingSecretKey: "keycloak-admin-password"

# Define realms and their clients below.
# If a realm does not exist, it will be created automatically.
# In the client parameters below, additionally you can define
#  secret: "optional-secret-value"
#  If not provided, a random secret is generated and stored in a K8s Secret
#  (Recommended)
realms:
  staff:
    clients:
      - clientId: openg2p-sr
        name: Social Registry
        redirectUris:
          - "*"
      - clientId: openg2p-registry
        name: Registry
        redirectUris:
          - "*"
      - clientId: openg2p-pbms
        name: PBMS
        redirectUris:
          - "*"
      - clientId: openg2p-superset
        name: Superset
        redirectUris:
          - "*"
        clientRoles:
          - "Admin"
      - clientId: openg2p-opensearch
        name: OpenSearch
        redirectUris:
          - "*"
        clientRoles:
          - "admin"
      - clientId: openg2p-kafka
        name: Kafka
        redirectUris:
          - "*"
        clientRoles:
          - "Admin"
      - clientId: openg2p-minio
        name: MinIO
        redirectUris:
          - "*"
        clientRoles:
          - "consoleAdmin"
      - clientId: openg2p-odk
        name: ODK
        redirectUris:
          - "*"
      - clientId: openg2p-spar
        name: SPAR
        redirectUris:
          - "*"
  agent:
    clients: []
  beneficiary:
    clients: []

job:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
